# Schema managed by Liquibase, Hibernate validates it matches.
spring.jpa.hibernate.ddl-auto=validate

# PostgreSQL database
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.datasource.hikari.maximum-pool-size=1

# JWT Security values and logging level.
security.jwt.signing.key=${JWT_SIGNING_KEY}
logging.level.org.springframework.security=warn

# Liquibase
spring.liquibase.enabled=true